# Generated by Django 5.2.11 on 2026-02-22 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('mob', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10-15 digits', regex='^\\d{10,15}$')])),
                ('linkedin', models.URLField()),
            ],
        ),
    ]
