# Generated by Django 5.2.11 on 2026-02-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotzenix', '0003_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Web_Development', models.CharField(max_length=255)),
                ('Mobile_App_Development', models.CharField(max_length=255)),
                ('Ecommerce_Development', models.CharField(max_length=255)),
                ('Digital_Marketing', models.CharField(max_length=255)),
                ('Salesforce_Development', models.CharField(max_length=255)),
            ],
        ),
    ]
