# Generated by Django 5.2.11 on 2026-02-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotzenix', '0004_menuitemservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemservices',
            name='Digital_Marketing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menuitemservices',
            name='Ecommerce_Development',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menuitemservices',
            name='Mobile_App_Development',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menuitemservices',
            name='Salesforce_Development',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menuitemservices',
            name='Web_Development',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
