# Generated by Django 5.2.11 on 2026-02-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotzenix', '0006_menuitemcompany_industries_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
            ],
        ),
    ]
