# Generated by Django 5.2.11 on 2026-02-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotzenix', '0006_menuitemcompany_industries_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='menuitemcompany',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='menuitemcompany',
            name='industries',
            field=models.CharField(blank=True, default=3, max_length=255),
            preserve_default=False,
        ),
    ]
