# Generated by Django 5.2.11 on 2026-02-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotzenix', '0007_menuitemproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemcompany',
            name='company_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menuitemcompany',
            name='industries_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
