# Generated by Django 5.2.11 on 2026-02-28 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotzenix', '0005_alter_menuitemservices_digital_marketing_and_more'),
        ('dotzenix', '0007_menuitemproducts_alter_menuitemcompany_company_and_more'),
        ('dotzenix', '0008_menuitemcompany_company_path_and_more'),
    ]

    operations = [
    ]
