# Generated by Django 5.2.11 on 2026-02-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotzenix', '0009_merge_20260228_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemcompany',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menuitemcompany',
            name='industries',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
