# Generated by Django 5.2.11 on 2026-02-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotzenix', '0010_alter_menuitemcompany_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemproducts',
            name='product_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='menuitemproducts',
            name='product',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
