# Generated by Django 5.2.11 on 2026-03-01 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotzenix', '0012_menuitemservices_path_dgit_menuitemservices_path_ec_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitemservices',
            name='Digital_Marketing',
        ),
        migrations.RemoveField(
            model_name='menuitemservices',
            name='Ecommerce_Development',
        ),
        migrations.RemoveField(
            model_name='menuitemservices',
            name='Mobile_App_Development',
        ),
        migrations.RemoveField(
            model_name='menuitemservices',
            name='Salesforce_Development',
        ),
        migrations.RemoveField(
            model_name='menuitemservices',
            name='Web_Development',
        ),
        migrations.RemoveField(
            model_name='menuitemservices',
            name='path_dgit',
        ),
        migrations.RemoveField(
            model_name='menuitemservices',
            name='path_ec',
        ),
        migrations.RemoveField(
            model_name='menuitemservices',
            name='path_mob',
        ),
        migrations.RemoveField(
            model_name='menuitemservices',
            name='path_sales',
        ),
        migrations.RemoveField(
            model_name='menuitemservices',
            name='path_web',
        ),
        migrations.RemoveField(
            model_name='menuitemservices',
            name='textec',
        ),
        migrations.RemoveField(
            model_name='menuitemservices',
            name='textgit',
        ),
        migrations.RemoveField(
            model_name='menuitemservices',
            name='textmob',
        ),
        migrations.RemoveField(
            model_name='menuitemservices',
            name='textsales',
        ),
        migrations.RemoveField(
            model_name='menuitemservices',
            name='textweb',
        ),
        migrations.AddField(
            model_name='menuitemservices',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='MenuItemServiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dotzenix.menuitemservices')),
            ],
        ),
    ]
