# Generated by Django 5.2.11 on 2026-03-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotzenix', '0013_remove_menuitemservices_digital_marketing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeddingSunhedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hedding', models.TextField(max_length=255)),
                ('subhedding', models.TextField(max_length=255)),
            ],
        ),
    ]
