# Generated by Django 5.2.11 on 2026-03-15 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotzenix', '0014_heddingsunhedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iconpath', models.ImageField(upload_to='card_images/')),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='heddingsunhedding',
            name='hedding',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='heddingsunhedding',
            name='subhedding',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='OurServiceSubitemCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subitem', models.CharField(blank=True, max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dotzenix.ourservicecard')),
            ],
        ),
    ]
