# Generated by Django 5.2.11 on 2026-03-15 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotzenix', '0015_ourservicecard_alter_heddingsunhedding_hedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourservicecard',
            name='iconpath',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ourservicesubitemcard',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subitems', to='dotzenix.ourservicecard'),
        ),
    ]
