# Generated by Django 5.2.11 on 2026-03-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotzenix', '0017_productcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionVission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtext', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
