# Generated by Django 5.2.11 on 2026-03-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotzenix', '0018_missionvission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satisfied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
