# Generated by Django 5.2.11 on 2026-03-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotzenix', '0019_satisfied'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=255)),
                ('tital', models.CharField(blank=True, max_length=225)),
                ('text', models.CharField(blank=True, max_length=255)),
                ('buttonlink', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
