# Generated by Django 5.2.11 on 2026-03-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotzenix', '0020_ourexpertise'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExploreOur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=255)),
                ('tital', models.CharField(blank=True, max_length=225)),
                ('text', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
