# Generated by Django 5.2.11 on 2026-03-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotzenix', '0021_exploreour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exploreour',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
